# Generated by Django 6.0.1 on 2026-01-28 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_surname', models.CharField(max_length=20)),
                ('second_surname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_names', models.CharField(blank=True, max_length=50)),
                ('employment_country', models.CharField(choices=[('CO', 'Colombia'), ('US', 'Estados Unidos')], max_length=2)),
                ('id_type', models.CharField(choices=[('CC', 'Cédula de Ciudadania'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PE', 'Permiso Especial')], max_length=2)),
                ('id_number', models.CharField(max_length=20)),
                ('email', models.CharField(editable=False, max_length=300, unique=True)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(choices=[('ADM', 'Administración'), ('FIN', 'Financiera'), ('COM', 'Compras'), ('INF', 'Infraestructura'), ('OPE', 'Operación'), ('TH', 'Talento Humano'), ('SV', 'Servicios Varios')], max_length=3)),
                ('status', models.CharField(default='Activo', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_surname', 'first_name'],
                'indexes': [models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'), models.Index(fields=['first_name', 'first_surname'], name='employees_e_first_n_006ffa_idx')],
                'unique_together': {('id_type', 'id_number')},
            },
        ),
    ]
